### ISSUE TITLE
The control end need to login before access

### ISSUE THREAD

**Issue by blackxd0g** [sctg-development/sctgdesk-api-server#14]
Hello. Rustdesk api pro has a useful feature in the settings.
The control end need to login before access. Is it possible to add this functionality?

**Comment by aeltorio** [comment]
Hi @blackxd0g,

Thank you for your suggestion! Since I don’t have access to Rustdesk Pro, could you please provide more details about this functionality? Specifically, how does the login process work and what benefits does it offer?

Best regards,
Ronan

**Comment by blackxd0g** [comment]
If the user is not logged in, he receives an error when connecting to any device in which the RustDesk server is registered.
You need to be logged in only for outgoing connections.

![image](https://github.com/user-attachments/assets/6ab73850-c226-4685-9e94-2ebe15b7bc86)
![image](https://github.com/user-attachments/assets/4f8b0814-b57d-4fa4-b3c2-af5298de2966)

**Comment by aeltorio** [comment]
Thank you for your answer, 
Is it a peer related setting ?
Could you capture the uncrypted exchange beetween the api server and you with Wireshark ? 
Ronan

**Comment by blackxd0g** [comment]
This setting is linked to the device IDs that fall into the default group after the server settings have been registered.. You can also link individual devices to individual groups and specify which group of users has access to them.

**Comment by aeltorio** [comment]
you need to start hbbs with `--logged-in-only` or set `LOGGED_IN_ONLY=Y` in your environment  
Ronan
