### ISSUE TITLE
Is this project 100% compatible with rustdesk-server?

### ISSUE THREAD

**Issue by MrChenhtlss** [sctg-development/sctgdesk-api-server#5]
If so I would move here. I use it as a production environment but I'm not a developer.
I can provide you with the latest questions and advice if you need it
Let's improve it together

![01240D8F-9618-4C3D-9943-77E90C3A0C08_1_201_a](https://github.com/sctg-development/sctgdesk-api-server/assets/146620104/c02d999f-c26a-4112-b5bb-5bdaf6b6b4c8)

**Comment by aeltorio** [comment]
# Response to Compatibility Question

Thank you for your interest in our project. I'd like to clarify a few points regarding your question:

## Project Scope and Compatibility

1. This project is solely an API server.
2. It is 100% compatible with the latest RustDesk client and the new address book API.

## Related Projects

Our parent project, [sctgdesk-server](https://github.com/sctg-development/sctgdesk-server), is a complete replacement for the RustDesk hbbs rendezvous server and includes this API server project.

## Database Compatibility

Currently, there's no automatic way to exchange databases between RustDesk Server Pro and sctgdesk-server. While they share the same structure, we face some challenges:

1. We don't have access to RustDesk Server Pro for testing.
2. The user password hash in RustDesk Server Pro is different from ours.

## Suggestion for Testing

If you have a RustDesk Server Pro database, you can try it with sctgdesk-server. However, you'll need to reset the admin password. For instructions on how to do this, please refer to our [Troubleshooting FAQ](https://github.com/sctg-development/sctgdesk-server/wiki/Troubleshooting#faq).

## Collaboration

We appreciate your offer to provide questions and advice. If you have specific insights or requirements based on your production environment, we'd be glad to hear them. Your input could be valuable in improving the project.

Feel free to open issues or discussions on our GitHub repository with any specific questions or suggestions you may have.
